### ISSUE TITLE
Add reviewes

### ISSUE THREAD

**Issue by JuanmaSemesur** [dim00z/gshoppingflux#83]
Hello,

It would be very interesting to add the reviews to the feed.

Thank you.

**Comment by Casper-O** [comment]
Hi

Last i checked documentations for Google Shopping Feed, it did not contain a review attribute.

As far i know you Can send in a separate feed with reviews, something im not going to do in this module

**Comment by JuanmaSemesur** [comment]
Hello,

Look at this website.

https://support.google.com/merchants/answer/6059553?hl=en

It seems that Google has already enabled it

Thank you.

**Comment by JuanmaSemesur** [comment]
Sorry I think I was wrong in the concept
I wanted to say Product Ratings
instead of review

Thank you.

**Comment by Casper-O** [comment]
Hi again.

The link you provided talkes about a ”product review feed”. It is an whole other feed, than the one this module provide. 

What your Looking for:
https://developers.google.com/product-review-feeds/

The google shopping feed, do not offer these details as you can see in the Specification for Google Shopping feed

https://support.google.com/merchants/answer/7052112?hl=en

Since it would require a separate feed I’m not going to add it to this module.
